#yaml para ejecutar funcionalPeroTard贸n al hacer push 
name: funcionalPeroTard贸n
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install transformers
        pip install torch torchvision torchaudio
        pip install pytest
        pip install tensorflow
        pip install tf-keras

    - name: Run tests
      run: |
        python -m pytest
    - name: Run functionalPeroTard贸n
      run: |
        python -m functionalPeroTard贸n.py
```