

name: Backend Diario de DailyDilemma

on:
  schedule:
    - cron: '30 8 * * *'
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create cred.json
      run: |
        echo '${{ secrets.FIREBASE_CREDENTIALS }}' > cred.json

    - name: Run First Python Script
      run: python extract_and_classify_news.py
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    - name: Run Second Python Script
      run: python generate_ethical_dilemmas.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Delete cred.json
      run: rm cred.json
